### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by KingKO04** [vishaalagartha/basketball_reference_scraper#22]
I would attempt to get stats from a team's roster and columns would be missing and replaced by a column of "..." (no matter how many columns were missing, it would be replaced by a singular column).
![image](https://user-images.githubusercontent.com/70914418/92413193-f4ffbb00-f11c-11ea-8978-db5673f84ccd.png)

**Comment by vishaalagartha** [comment]
This is expected behavior. The return type of `get_stats` is a pandas dataframe, which does not show the entire result if the number of rows/columns is too large. Your return value says `[19 rows x 30 columns]`, so the data is clearly returned. 

In order to see the entire dataframe, refer to [this link.](https://www.kite.com/python/answers/how-to-print-an-entire-pandas-dataframe-in-python#:~:text=Use%20pandas.,to%20be%20displayed%20when%20printed)

**Comment by vishaalagartha** [comment]
Try this code snippet out:

```
import pandas as pd
from basketball_reference_scraper.teams import get_roster_stats
pd.set_option("display.max_rows", None, "display.max_columns", None)
df = get_roster_stats('DAL', 2020, data_format='TOTALS', playoffs=False)
print('==========Entire dataframe=======')
print(df)

# To print a specific column, like 2P%
print(df['2P%'])
```

You may be more comfortable with python lists, so you could always convert a column like `l = list(df['2P%'])`, but I would encourage you to learn to use pandas since it is so prevalent in data analysis.
